# Generated by Django 2.1 on 2022-12-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallThumbnail', models.CharField(max_length=122)),
                ('thumbnail', models.CharField(max_length=122)),
                ('title', models.CharField(max_length=122)),
                ('subtitle', models.CharField(max_length=122)),
                ('authors', models.CharField(max_length=122)),
                ('publishedYear', models.CharField(max_length=122)),
                ('description', models.CharField(max_length=122)),
            ],
        ),
    ]
