# Generated by Django 2.1 on 2022-12-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
