# Generated by Django 2.1 on 2022-12-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksStore', '0002_auto_20221203_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishedYear',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='books',
            name='subtitle',
            field=models.CharField(max_length=30),
        ),
    ]
