# Generated by Django 2.1 on 2022-12-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksStore', '0003_auto_20221203_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
