# Generated by Django 2.1 on 2022-12-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksStore', '0004_auto_20221206_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
