# Generated by Django 2.1 on 2022-12-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksStore', '0005_auto_20221206_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='publishedYear',
        ),
    ]
